version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS="-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - police-pr-elastic-data:/usr/share/elasticsearch/data
    networks:
      - police-pr
    restart: always

  police-pr-search:
    build: .
    depends_on:
      - elasticsearch
    restart: always
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - police-pr



volumes:
  police-pr-elastic-data:
    driver: local

networks:
  police-pr:
    driver: bridge
