version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./police-pr-elastic-data:/usr/share/elasticsearch/data
    networks:
      - police-pr
    restart: always

  police-pr-search:
    build: .
    depends_on:
      - elasticsearch
    restart: always
    environment:
      - ELASTIC_HOST=elasticsearch
    expose:
      - 8000
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:police-pr-search.robin-in.space"
      - "traefik.basic.port=8000"
      - "traefik.basic.protocol=http"
    networks:
      - web
      - police-pr


networks:
  police-pr:
    driver: bridge
  web:
    external: true
